# Generated by Django 2.2.6 on 2020-04-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', help_text='Employee Name', max_length=30)),
                ('age', models.PositiveSmallIntegerField(default=50, help_text='Vacation Days')),
            ],
        ),
    ]
